FROM node:16-alpine as base

WORKDIR /src
COPY package*.json /
EXPOSE 3000

FROM base as builder
RUN npm i
ENV NODE_ENV=production
COPY . .
RUN npm run build

FROM node:16-alpine as production
WORKDIR /src

# COPY --from=builder /src/node_modules ./node_modules
# COPY --from=builder /src/public ./public
# COPY --from=builder /src/package.json ./package.json
COPY --from=builder /src .

CMD ["next", "start"]


FROM base as dev
ENV NODE_ENV=development
RUN npm install -g nodemon && npm install
COPY . /
CMD ["npm", "run", "dev"]
