version: "3.3"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    ports:
       - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - mydb:/var/lib/mysql

  backend:
    container_name: klinik_backend
    command: npm run dev
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    env_file: ./.env
    environment:
      STATIC_IMG_DIR: ${STATIC_IMG_DIR}
      DB_HOST: mysqldb
      DB_PORT: ${MYSQLDB_DOCKER_PORT}
      DB_USER: ${MYSQLDB_USER}
      DB_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      DB_DATABASE: local_db
      TOKEN_SECRET: ${TOKEN_SECRET}
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    depends_on:
      - mysqldb
    volumes:
      - ./backend:/src
      - /src/node_modules

  frontend:
    container_name: klinik_frontend
    build:
      context: ./app
      dockerfile: Dockerfile
      target: production
      args:
        TOKEN_SECRET: ${TOKEN_SECRET}
        BACKEND_API: ${NEXT_BACKEND_API}
    command: npm run start
    env_file: ./.env 
    ports:
      - ${NEXT_LOCAL_PORT}:${NEXT_DOCKER_PORT}
    volumes:
      - ./app/public:/src/public
      # - ./app:/src
      # - /src/node_modules
volumes: 
  mydb: